{% set name = "libxkbcommon" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/xkbcommon/{{ name }}/archive/xkbcommon-{{ version }}.tar.gz
  sha256: 270e2ad4ce5699f633e49042114cb68a5697fa1ed45b65c1d96a833cfac20954

build:
  number: 1
  skip: true  # [win or s390x or ppc64le or osx]
  missing_dso_whitelist:
    - "*/libc.so.6"
    - /lib/libc.so.6
  run_exports:
    - {{ pin_subpackage('libxkbcommon') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ cdt('libxau-devel') }}
    - meson
    - ninja
    - m4
    - bison
    - cmake
    - pkg-config
  host:
    - libxcb
    - libxml2
    - xorg-xproto
    - xcb-proto
    - pthread-stubs

test:
  commands:
    - test -f "${PREFIX}/lib/libxkbcommon${SHLIB_EXT}"

about:
  home: https://github.com/xkbcommon/libxkbcommon
  license: MIT/X11 Derivative
  license_family: MIT
  license_file: LICENSE
  summary: 'keymap handling library for toolkits and window systems'
  description: |
    libxkbcommon is a keyboard keymap compiler and support library which
    processes a reduced subset of keymaps as defined by the XKB (X Keyboard
    Extension) specification.
  doc_url: https://xkbcommon.org/
  dev_url: https://github.com/xkbcommon/libxkbcommon

extra:
  recipe-maintainers:
    - scopatz
