{% set name = "libxkbcommon" %}
{% set version = "1.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/xkbcommon/{{ name }}/archive/xkbcommon-{{ version }}.tar.gz
  sha256: 763b914c4779e9579ab4d06caffff39cc8f43a1c126ec3b7a2f920bf9817097b

build:
  number: 0
  skip: true  # [win or osx]
  run_exports:
    - {{ pin_subpackage('libxkbcommon') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - meson
    - ninja
    - m4
    - bison
    - cmake
    - pkg-config
  host:
    - xorg-libxau
    - libxcb
    - xorg-xorgproto
    - xcb-proto
    - pthread-stubs
    - libxml2 {{ libxml2 }}
  run:
    - xkeyboard-config

test:
  commands:
    - test -f "${PREFIX}/lib/libxkbcommon${SHLIB_EXT}"
    - xkbcli --help

  # Check downstream packages if needed.
  # downstreams:
  #   - qtbase
  #   - qtwebengine
  #   - nsight-compute

about:
  home: https://xkbcommon.org/
  license: MIT AND X11
  license_family: MIT
  license_file: LICENSE
  summary: keymap handling library for toolkits and window systems
  description: |
    libxkbcommon is a keyboard keymap compiler and support library which
    processes a reduced subset of keymaps as defined by the XKB (X Keyboard
    Extension) specification.
  doc_url: https://xkbcommon.org/doc/current/
  dev_url: https://github.com/xkbcommon/libxkbcommon

extra:
  recipe-maintainers:
    - scopatz
    - hmaarrfk
